// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    databaseURL: 'https://vinyl-rental-default-rtdb.europe-west1.firebasedatabase.app/',
    apiKey: 'AIzaSyDeRm0njG_tIsj64w9kHKuiNw3bsLx6qHo',
    appId: '1:732744375960:web:18f9dfef0c9256861cfaed',
    messagingSenderId: '732744375960',
    projectId: 'vinyl-rental',
    authDomain: 'vinyl-rental.firebaseapp.com',
    storageBucket: 'vinyl-rental.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    databaseURL: 'https://vinyl-rental-default-rtdb.europe-west1.firebasedatabase.app/',
    apiKey: 'AIzaSyCc9kEb80ifFEG-AT0ji6z2aNwMcA8xcG0',
    appId: '1:732744375960:android:5e2b7bfe423f51881cfaed',
    messagingSenderId: '732744375960',
    projectId: 'vinyl-rental',
    storageBucket: 'vinyl-rental.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALo-8AvwdMm_FYRXOHArhqBlTq67RC5oo',
    appId: '1:732744375960:ios:169858a4773f74631cfaed',
    messagingSenderId: '732744375960',
    projectId: 'vinyl-rental',
    storageBucket: 'vinyl-rental.appspot.com',
    iosClientId: '732744375960-hfafgkgdkqcocn1f7jq1lb26viie8kb7.apps.googleusercontent.com',
    iosBundleId: 'com.example.vinylRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALo-8AvwdMm_FYRXOHArhqBlTq67RC5oo',
    appId: '1:732744375960:ios:169858a4773f74631cfaed',
    messagingSenderId: '732744375960',
    projectId: 'vinyl-rental',
    storageBucket: 'vinyl-rental.appspot.com',
    iosClientId: '732744375960-hfafgkgdkqcocn1f7jq1lb26viie8kb7.apps.googleusercontent.com',
    iosBundleId: 'com.example.vinylRental',
  );
}
